# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: employee-api
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "2"

provider:
  name: aws
  runtime: java8  #use at fn lv.
  lambdaHashingVersion: 20201221
  environment: #12 factor app ---|----use param store & secret store
    RDS_HOSTNAME: my-db.cvbik3j8hhjj.${self:provider.region}.rds.amazonaws.com:3306
    RDS_DB_NAME: emp_db
    RDS_USERNAME: ${ssm:/dev/south/rds/username~true}
    RDS_PASSWORD: ${ssm:/dev/south/rds/password~true}
  vpc:
    securityGroupIds:
      - Ref: LambdaSecurityGroup
      - Ref: DbSecurityGroup
    subnetIds:
      - Ref: PrivateSubnet1
      - Ref: PrivateSubnet2
      - Ref: PrivateSubnet3

# you can add packaging information here
package:
  # artifact: target/hello-dev.jar
  artifact: "target/${self:service}-${self:provider.stage}.jar"

functions:
  employee:
    handler: com.serverless.Handler
    events:
      - httpApi:
          path: /db
          method: get

# you can add CloudFormation resource templates here
resources:
- ${file(./Infra/Network/network.yml)}
- ${file(./Infra/Compute/compute.yml)}
- ${file(./Infra/Storage/storage.yml)} 