# --------------------------RDS Database--------------------------------
Resources:
  DbSubnetGroup:
      Type: "AWS::RDS::DBSubnetGroup"
      Properties:
        DBSubnetGroupName: db-${self:service}-${self:provider.stage}
        DBSubnetGroupDescription: Private database subnet group
        SubnetIds:
          - Ref: PrivateSubnet1
          - Ref: PrivateSubnet2
          - Ref: PrivateSubnet3

  EmployeeDb:
      Type: AWS::RDS::DBInstance
      Properties:
        DBInstanceIdentifier: my-db
        DBName: emp_db
        DBInstanceClass: db.t2.micro
        AllocatedStorage: "20"
        Engine: mysql
        EngineVersion: 8.0.16
        MasterUsername: ${ssm:/dev/south/rds/master_username~true}
        MasterUserPassword: ${ssm:/dev/south/rds/master_password~true}
        VPCSecurityGroups:
          - Ref: DbSecurityGroup
        DBSubnetGroupName:
          Ref: DbSubnetGroup

    # DBUsername:
    #     NoEcho: 'true'
    #     Description: Username for MySQL database access
    #     Type: String
    #     MinLength: '1'
    #     MaxLength: '16'
    #     AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    #   DBPassword:
    #     NoEcho: 'true'
    #     Description: Password MySQL database access
    #     Type: String
    #     MinLength: '8'
    #     MaxLength: '41'
    #     AllowedPattern: '[a-zA-Z0-9]*'  